---
version: '3'
tasks:
  doc:
    cmds:
      - gomarkdoc $(go list ./... | grep -v example) > doc/README.md
  deeplint:
    cmds:
      - golangci-lint run --enable-all
  test:
    cmds:
      - go test $(go list ./... | grep -v example)
